package parse

// Any returns a Parser, the result of which is generated by attempting the
// provided Parsers in succession. The first Parser that returns a Success ends
// the processing, and its Success instance is returned
func Any(first Parser, rest ...Parser) Parser {
	if len(rest) > 0 {
		return Or(first, Any(rest[0], rest[1:]...))
	}
	return first
}

// Optional returns a new Parser that will DefaultTo nil if the match is not
// successful
func Optional(p Parser) Parser {
	return DefaultTo(p, nil)
}

// DefaultTo returns a new Parser that will return the provided result if the
// provided Parser match is not successful
func DefaultTo(p Parser, r any) Parser {
	return Or(p, Return(r))
}
